default:
  app:
    annotations:
      annotation: test
    labels:
      label: test
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/parthghetia-rh/spoke-cluster-config.git
      targetRevision: HEAD
      
projects:

  cluster-config:
    annotations:
      project: test
    labels:
      project: test
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - https://github.com/parthghetia-rh/spoke-cluster-config
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'


applications:

  config-app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '21'
    source:
      path: clusters/dev/spoke-1.redhat.com/app-simple-1

  