{{- range .Values.namespaces }}
  {{- $namespace := .name }}
  {{- range .secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: {{ .url | quote }}
  type: {{ .type | quote }}
  username: {{ .username | quote }}
  password: {{ .password | quote }}
  {{- end }}
{{- end }}
