namespaces:
  - name: openshift-gitops
    secrets:
      - name: argoproj-https-creds
        url: https://github.com/argoproj
        type: helm
        username: my-username
        password: my-password #secrets should be stored externally with the usage of an external secrets manager
  - name: openshift-operators
    secrets:
      - name: argoproj-https-creds-test
        url: https://github.com/argoproj
        type: git
        username: my-username-test
        password: my-password-test
  - name: wordpress-test
    secrets:
      - name: argoproj-https-creds-wordpress
        url: https://github.com/argoproj
        type: git
        username: my-username-wordpress
        password: my-password-wordpress
  
